#!/usr/bin/env bash
#Display usage if less than 4 parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Use scp to transfer the file to the user's home directory on the server
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username"@"$server_ip":~/

echo "File transferred successfully!"