#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.
#+    Configures servers with correct hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.

STUDENT_ID="531439" 
WEB_01_IP="18.204.7.96" 
WEB_02_IP="35.174.211.88"  

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind dev.shaaleh.tech:80
    mode http
    option http-keep-alive
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server ${STUDENT_ID}-web-01 ${WEB_01_IP} check
    server ${STUDENT_ID}-web-02 ${WEB_02_IP} check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
