#!/usr/bin/env bash
#FizzBuzz when number is multiple of 3 and 5 Buzz when is of 3 and Fizz when is of 5, otherwise number is displayed

i=1
while [ $i -le 100 ]
do
	if (( i % 3 == 0 && i % 5 == 0))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0))
	then
		echo "Fizz"
	elif (( i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	(( i++ ))
done
