#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file using a while loop + IFS

# Set the IFS to ':' to parse the fields in /etc/passwd
IFS=":"

# Read each line of the /etc/passwd file
while read -r username password uid gid info home shell; do
    echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"